### ISSUE TITLE
Some services are not able to be constructed

### ISSUE THREAD

**Issue by Flex-Xuan** [serverlessworkflow/sdk-net#47]
**What happened**:
After inject the serverless workflow, the application cannot run successfully

**How to reproduce it**:

Install the Serverlessworkflow.0.8.7 , then 
![image](https://github.com/serverlessworkflow/sdk-net/assets/22612605/5f43e008-b8fe-45a4-893b-fed777811457)

**Comment by cdavernas** [comment]
Thanks for reporting! I'll have a look, thanks!

**Comment by Flex-Xuan** [comment]
> Thanks for reporting! I'll have a look!

It seems there is no place to 'inject' those state definitions , so when the service collection resolve the validator, the definitions can not be resolved.

If I try to manually register those definitions, this issue seems gone. But I still don't know why

![image](https://github.com/serverlessworkflow/sdk-net/assets/22612605/c328ffb7-1fc1-45a5-ae5b-0793f7811485)

**Comment by Flex-Xuan** [comment]
> I think there's an artefact being carried over from my last refactor. I'll check it out this afternoon.

Another thing I found is when I using ODataConventionModelBuilder to get the EdmModel, it will throw exceptions likes bellow,

![image](https://github.com/serverlessworkflow/sdk-net/assets/22612605/27672dbb-10e7-4fa6-bf56-07f7a94987e5)

This seems that the Definition implemented both IMetadata and IExtensible, if I comment Metadata out, this issue gone. is there any solution on this?

Thanks a lot.

**Comment by Flex-Xuan** [comment]
> > I think there's an artefact being carried over from my last refactor. I'll check it out this afternoon.
> 
> Another thing I found is when I using ODataConventionModelBuilder to get the EdmModel, it will throw exceptions likes bellow,
> 
> ![image](https://private-user-images.githubusercontent.com/22612605/290151302-27672dbb-10e7-4fa6-bf56-07f7a94987e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjUxODIsIm5iZiI6MTcwMjUyNDg4MiwicGF0aCI6Ii8yMjYxMjYwNS8yOTAxNTEzMDItMjc2NzJkYmItMTBlNy00ZmE2LWJmNTYtMDdmN2E5NDk4N2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAzMzQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZTg2NjUyZjQwYzJmMTliMDg2MjljOTg2YzQ1NjYzOTJmZTQxYmFjOWQ1OWJlMDkxOTViOGI2N2FlYWQ2NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._MaZ21zttJYXBzmAWMju6tsuIVuJ1fvysay7QUAn_BQ)
> 
> This seems that the Definition implemented both IMetadata and IExtensible, if I comment Metadata out, this issue gone. is there any solution on this?
> 
> Thanks a lot.

I think the type 'DynamicMapping' doesn't need to implement IDictionary<String,Object>, because it already contains an property with type IDictionary<String,Object>, and it is public get, so those Add, ContainsKey, etc methods already exposed. I don't know if I am right or not.

**Comment by Flex-Xuan** [comment]
I am curious that, for example  [FunctionReference Definition](https://github.com/serverlessworkflow/specification/blob/main/specification.md?plain=1#functionref-definition) in the spec, it doesn't has 'additional properties', but in the sdk why it implemented IExtensible, also?

**Comment by cdavernas** [comment]
@Flex-Xuan Sorry for the delay, I have a lot on my plate! 
Extensible and metadata are two different things. The first is used by eventual extensions of the spec to add new properties and features, whereas the metadata provides additional properties to describe the object, and is serdes as its own property instead of being merged at top level.
So far, only metadata was supported, both for description and as a supposed mechanism for extending some specific components. 
This was, imho, not enough, and felt to be a kinduv trick.
If you want to know more about said extensions, please don't hesitate to join weeklies, so that we can showcase extension merge patches, for instance. I guess the doc about those will make it to 0.9
