### ISSUE TITLE
Is this SDK still under development state?

### ISSUE THREAD

**Issue by Flex-Xuan** [serverlessworkflow/sdk-net#56]
**What is the question**: Is this SDK still under development state?  

I want to know when the next version of this SDK will be release, because I see many changes on the specifications, for example, https://github.com/serverlessworkflow/specification/issues/686  . If I want to contribute on this SDK, what should I do? which branch should I checkout and working on?

**Comment by cdavernas** [comment]
Hello @Flex-Xuan and thank you for your interest!

The SDK is still active! We are waiting for SW 0.9 for next release, which includes the PR you mentionned and many more.

As for contributing, which you are very welcome to, you should prefer using `main`. 

Hope this answers your questions!

**Comment by Flex-Xuan** [comment]
Ok, understood. Do you know when SW 0.9 will be finished.

**Comment by Flex-Xuan** [comment]
It seems the SW 0.9 was released, when will we released the new SDK?

**Comment by cdavernas** [comment]
Do you need the 0.9? Reason I ask Is before the 1.0.0-alpha1 is gonna be released this week or next, and is a major overhaul of the spec, and I was thinking to skip the 0.9 and go straight to it.
If you fo need it, any chance you are up to contribute to it? Would allow me to keep focus on the upcoming DSL and Synapse.

**Comment by cdavernas** [comment]
Closing issue as stale
