### ISSUE TITLE
Suggest remove the Extensions

### ISSUE THREAD

**Issue by wjqdst** [serverlessworkflow/sdk-net#61]
<img width="596" alt="WXWorkCapture_17267126618091" src="https://github.com/user-attachments/assets/31b7ff4a-dbfb-4937-ad7d-d11b6e9e5c99">
<img width="696" alt="WXWorkCapture_17267126522149" src="https://github.com/user-attachments/assets/f2374987-fa97-4b2f-b2b8-be027a48ad76">
<img width="557" alt="WXWorkCapture_17267126146476" src="https://github.com/user-attachments/assets/2210614d-994e-489f-8522-234772dca32d">
Hi,
Because now in the TaskDefinition have 2 EquatableDictionary parameter, 1 is Extensions another is Metadata, but if we use odata it will casue error, and I see in the document we just have Metadata do not have Extensions, so I suggest to remove the Extensions parameter.
Thanks.

**Comment by evil116** [comment]
when will the issue be resolved?

**Comment by evil116** [comment]
when will the issue be resolved? @cdavernas

**Comment by cdavernas** [comment]
@evil116  Not before next week as I'm in PTO.

**Comment by wjqdst** [comment]
@cdavernas noted with thanks, when you work next week, please let us know whether your team will fix this and when will have a new release for this. 😉

**Comment by wjqdst** [comment]
@cdavernas may I know this progress

**Comment by cdavernas** [comment]
Still on PTO. As said, I'll try to solve it this week 😉 I'll keep you posted.

In the meanwhile, please do drop a star 🙏

**Comment by wjqdst** [comment]
noted, already drop.

**Comment by wjqdst** [comment]
@cdavernas may I know the progress again

**Comment by cdavernas** [comment]
Merging in progress.

On a side note, and even though the `extensions` property was not required anymore, the `metadata` one should NOT be considered as an ODATA extension property: unlike `extensions`, it should be queryable just like any other top level properties.
To do so, you'd need to register `EquatableDictionary<string, object>` as a new complex type, or using a surrogate list type (ex: KvpList<T>)
