### ISSUE TITLE
What is the correct name of property? "arguments" or "parameters"

### ISSUE THREAD

**Issue by Flex-Xuan** [serverlessworkflow/sdk-net#72]
**What is the question**: 

In the spec, we can see the name is "arguments"
![image](https://github.com/user-attachments/assets/dbe66f0f-e08f-4504-a7ea-e95c81989891)
but in the sdk, we can see it is "parameters"
![image](https://github.com/user-attachments/assets/8150fe93-b94a-4688-8641-d47cd1e78d3e)

so which is correct?

**Comment by cdavernas** [comment]
The documentation is incorrect, as per [schema](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.yaml#L392), it is `Parameters`.

Could I ask you to open an issue on the spec to address that error?

**Comment by Flex-Xuan** [comment]
> The documentation is incorrect, as per [schema](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.yaml#L392), it is `Parameters`.
> 
> Could I ask you to open an issue on the spec to address that error?

Sure, glad to do that. Issue [created](https://github.com/serverlessworkflow/specification/issues/1042)

**Comment by cdavernas** [comment]
Many thanks! Closing this one as a matter of consequence 😉
